- name: PLAY1
  hosts: local 
  connection: local 
  tasks:
    - name: PLAY1 and TASK1
      ansible.builtin.plugin:
        msg: "Hi this is from Play1 and Task1"


- name: PLAY2
  hosts: local
  connection: local 
  tasks: 
    - name: Play2 and Task2
      ansible.builtin.plugin:
        msg: "Hi this is from Play2 and Task2"