- name: Task level vars
  hosts: local
  connection: local 
  vars:
    COURSE: DevOps
    DURATION: 2 months
    TRAINER: siva

  tasks:
  - name: print variable in play
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }},Duration is {{ DURATION }},Trainer is {{ TRAINER }}"
  
  - name: Print variables in task  
    vars:
      COURSE: DevSecOps 
    ansible.builtin.debug:   
      msg: "Course is {{ COURSE }},Duration is {{ DURATION }},Trainer is {{ TRAINER }}"