- name: Prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false
  - name: DURATION
    prompt: please enter duration
    private: false 
  - name: TRAINER
    prompt: please enter time
    private: false

  tasks: 
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }},Time is {{ TRAINER }}"